[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "task-cli"
description = "Example package for a CLI"
authors = [{name="You", email="you@example.com" }]
version = "0.0.0"
dependencies = []

[project.scripts]
task-cli = "src.app:main"
